Name: Jignesh Tathe

Branch: CO

Assignment_no.3

# *numpy Functions*

In [13]:
import numpy as jig
arr=jig.array([1,2,3,4,5])

In [40]:
print(arr)

[1 2 3 4 5]


# 1. Sort

In [6]:
new_arr= jig.array([12,3,1,4,5,6])

In [8]:
jig.sort(new_arr)

array([ 1,  3,  4,  5,  6, 12])

In [11]:
jig.sort(new_arr) > 5

array([False, False, False, False,  True,  True])

# 2. Clip

In [15]:
jig.clip(arr, 2, 4)

array([2, 2, 3, 4, 4])

# 3. Round

In [19]:
arr1=jig.array([1.223,2.367])

In [21]:
jig.round(arr1,1)

array([1.2, 2.4])

# 4. Floor

In [24]:
arr2=jig.array([1.2, 2.8, 4.5, 3.1, 67.9, 89.3, 10.7])

In [42]:
jig.floor(arr2)

array([ 1.,  2.,  4.,  3., 67., 89., 10.])

# 5. ceil

In [26]:
arr2

array([ 1.2,  2.8,  4.5,  3.1, 67.9, 89.3, 10.7])

In [29]:
jig.ceil(arr2)

array([ 2.,  3.,  5.,  4., 68., 90., 11.])

# 6. intersect

In [32]:
a = jig.array([1, 2, 3])
b = jig.array([3, 4, 5])

jig.intersect1d(a, b)    # [3]

array([3])

# 7. union

In [33]:
jig.union1d(a, b)        

array([1, 2, 3, 4, 5])

# 8. set difference

In [34]:
jig.setdiff1d(a, b)

array([1, 2])

# 9. Sum

In [35]:
arr3=jig.array([10,20,30,40,50])

In [36]:
jig.sum(arr3)

np.int64(150)

# 10. Product

In [37]:
arr4= jig.array([5,4,3,2,1])

In [39]:
jig.prod(arr4)

np.int64(120)